// <auto-generated />
namespace WebApplicationCTDEO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Nova_configuracao_NparaN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nova_configuracao_NparaN));
        
        string IMigrationMetadata.Id
        {
            get { return "201807241235189_Nova_configuracao_NparaN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
