// <auto-generated />
namespace WebApplicationCTDEO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class atualizacao_modalidadeeturma : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(atualizacao_modalidadeeturma));
        
        string IMigrationMetadata.Id
        {
            get { return "201808191334470_atualizacao_modalidadeeturma"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
