// <auto-generated />
namespace WebApplicationCTDEO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class edicao_de_campos_alunos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edicao_de_campos_alunos));
        
        string IMigrationMetadata.Id
        {
            get { return "201809091350452_edicao_de_campos_alunos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
