// <auto-generated />
namespace WebApplicationCTDEO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deixando_valores_de_Modalidade_anulaveis : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deixando_valores_de_Modalidade_anulaveis));
        
        string IMigrationMetadata.Id
        {
            get { return "201808272353210_deixando_valores_de_Modalidade_anulaveis"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
