// <auto-generated />
namespace WebApplicationCTDEO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deletando_coluna_dias : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletando_coluna_dias));
        
        string IMigrationMetadata.Id
        {
            get { return "201808292353332_deletando_coluna_dias"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
