// <auto-generated />
namespace WebApplicationCTDEO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tirando_generalização_modalidades : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tirando_generalização_modalidades));
        
        string IMigrationMetadata.Id
        {
            get { return "201808192316228_tirando_generalização_modalidades"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
