// <auto-generated />
namespace WebApplicationCTDEO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adicao_de_colunas_de_dias : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicao_de_colunas_de_dias));
        
        string IMigrationMetadata.Id
        {
            get { return "201808292347149_adicao_de_colunas_de_dias"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
