// <auto-generated />
namespace WebApplicationCTDEO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Correcao_de_Chave_Estrangeira_na_Turma : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Correcao_de_Chave_Estrangeira_na_Turma));
        
        string IMigrationMetadata.Id
        {
            get { return "201807191654322_Correcao_de_Chave_Estrangeira_na_Turma"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
