// <auto-generated />
namespace WebApplicationCTDEO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Remocao_tabela_responsavel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remocao_tabela_responsavel));
        
        string IMigrationMetadata.Id
        {
            get { return "201807221507169_Remocao_tabela_responsavel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
