// <auto-generated />
namespace WebApplicationCTDEO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Exclusao_de_tabelas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Exclusao_de_tabelas));
        
        string IMigrationMetadata.Id
        {
            get { return "201807191936193_Exclusao_de_tabelas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
