// <auto-generated />
namespace WebApplicationCTDEO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modificacao_temporario_de_atributoturma_em_aluno1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modificacao_temporario_de_atributoturma_em_aluno1));
        
        string IMigrationMetadata.Id
        {
            get { return "201809011534096_modificacao_temporario_de_atributoturma_em_aluno1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
