// <auto-generated />
namespace WebApplicationCTDEO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class novo_atributo_modalidade3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(novo_atributo_modalidade3));
        
        string IMigrationMetadata.Id
        {
            get { return "201808132258565_novo_atributo_modalidade3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
