// <auto-generated />
namespace WebApplicationCTDEO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Adicao_de_AlocacaodeAluno1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adicao_de_AlocacaodeAluno1));
        
        string IMigrationMetadata.Id
        {
            get { return "201807191723471_Adicao_de_AlocacaodeAluno1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
