// <auto-generated />
namespace WebApplicationCTDEO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modificacao_nome_atributo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modificacao_nome_atributo));
        
        string IMigrationMetadata.Id
        {
            get { return "201807301237291_modificacao_nome_atributo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
